### ISSUE TITLE
Allow `.solution.toml` files to run the current buffer

### ISSUE THREAD

**Issue by mesa123123** [Zeioth/compiler.nvim#35]
Basically what it says on the tin.

The imports I'm putting in my files are all relative to the root directory so the scripts needs to be run as:

"python -m src.script"

as opposed to:

python script.py

therefore i"m getting an error that says:
no module named src

**Comment by mesa123123** [comment]
I've added my own fix here:
https://github.com/Zeioth/compiler.nvim/pull/36

**Comment by Zeioth** [comment]
Hello @mesa123123 thank you for your PR but this is already possible within our current architucture.

Create `.solution.toml` in your project working directory
```
[MyCoolProgram]
entry_point = "./src.script"
arguments = "-m"
```

That will run `python -m ./src.script`.

**Comment by Zeioth** [comment]
It's documented on the readme in the examples of creating a solution [here](https://github.com/Zeioth/Compiler.nvim/wiki/solution-examples).

To understand where to use every option of the compiler, check [here](https://github.com/Zeioth/compiler.nvim/wiki/When-to-use-every-option).

**Comment by mesa123123** [comment]
I saw that but I feel like it'd be nice to have it for a different use case where you've got multiple files that needs to be run in this fashion? 

Rather than making a .solution.toml and having:

```toml
[Mysolutionfile1]
entry_point = ./.src.point1
cmd = python -m

[Mysolutionfile2]
entry_point = ./.src.point2
cmd = python -m

[Mysolutionfile3]
entry_point = ./.src.point3
cmd = python -m
```
And having to add to this as different files become available you can just have a solution that figures it out for you?

Why I'm running python in this way is that it works out that imports are MUCH clearer, i.e. you can use pytest, python, and pylint in an "it just works" manner
They all understand "import src.module" whereas relative imports break some and not others.
